name: lapor_book
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.5
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  provider: ^6.1.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/upload.png
    - assets/inovation.png
